Desktop version
MasumaJaffery/Module-Capstone-1 pull request #2
Opened 2023-05-24 20:59 UTC by MasumaJaffery

2023-05-24 23:17 UTC, taldr27 requested changes
# Status: Required Changes ♻️♻️
Hello @MasumaJaffery , 

Good job so far! 
You're making good progress on the project, but some issues still need to be addressed before you can move on to the next stage. Keep up the good work! 💪

![almost-there](https://media.giphy.com/media/l1JojjVanlckKIHMQ/giphy.gif)

## Highlights 🎉
✅ Professional and customized README. 
✅ Linters tests passing.
✅ Correct use of GitHub Flow.
✅ Great use of animations.
✅ Great work with your JavaSript code.

## Required Changes ♻️
_Check the comments under the review._

------
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-05-24 23:17 UTC, taldr27 commented on index.html
>              <h2>Main Programs</h2>
Great job with your Main program section! I have some suggestions to help you achieve a closer resemblance to the Behance design. Remember, adhering to the specified sizes, fonts, and colors is a requirement for this project:

- [ ] Please review the size of your images, as it appears to be too large in all your elements. This is causing limitations in adding sufficient padding to your content. **Adjusting the image size will allow for better alignment and spacing.** 😃

- [ ] Kindly verify the size of your `button`, as it does not match the [provided design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). It's important to align it with the design to ensure consistency throughout your project. 👍

- [ ] Check the `font-weight` you are applying in your text. It seems that you are using a heavier weight than what is specified in the design. Make sure to **use the correct `font-weight` to maintain consistency with the provided design**. 😃

   ### Your design:
   ![image](https://github.com/MasumaJaffery/Module-Capstone-1/assets/107952724/74e57b76-62e1-4704-a5df-e5f8c95ad423)

   ### Behance design:
   ![image](https://github.com/MasumaJaffery/Module-Capstone-1/assets/107952724/fc49f266-e7fe-4ca5-933c-bf8ebc9b0cc9)

  _Just a friendly reminder that following the provided template is a key requirement for this project. You're doing a great job so far, and it's important to keep the template in mind as you continue with your design to ensure that your project meets all of the project requirements._
  ![image](https://github.com/MariamOsman11/CAPSTONE-PROJECT-ONE/assets/107952724/d0b9a412-cbf1-4665-b622-cc89958dfb40)

2023-05-24 23:17 UTC, taldr27 commented on index.html
> +        <a href = "index.html"><img class = "logo" src = "Images/Logo.png"></a>
- [ ]  It's always recommended to add an `alt` attribute to all the images in your project **for accessibility purposes**. This will ensure that your project is more inclusive and accessible to everyone. 🤓

2023-05-25 10:22 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/7SyGkO0kQWCfnUC47Y/giphy.gif)


# Hi @MasumaJaffery 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- UI is a good replica of original design ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a good summary ✔

 ## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 10:22 UTC, AbelG101 commented on style.css
https://github.com/MasumaJaffery/Module-Capstone-1/blob/36781d7f523a9cd7f76538034dc45798b2c6464e/style.css#L98-L102
- [ ] As mentioned previously there seems to be an excessive space between the landing page and the middle section of the home page and this is causing discrepancies between your design and the Behance one. This is mainly because the `height: 100vh` from the above `header` selector so kindly remove it and then you can add a `margin-bottom` to the `.content` selector at line `167`. 😉
- Your design:
  ![image](https://github.com/MasumaJaffery/Module-Capstone-1/assets/104968236/fe9fc0b5-b1e0-4e6e-b558-df1b0c03808b)
- Behance design:
  ![image](https://github.com/MasumaJaffery/Module-Capstone-1/assets/104968236/2f986167-fd7a-4129-95cc-a393268381d6)
- After applying the above recommendations I've mentioned previously It'll look something like this:
    ![firefox_PGfJWouRoU](https://github.com/MasumaJaffery/Module-Capstone-1/assets/104968236/a2eff18b-9fa0-4c45-ab16-707537fa1311)

2023-05-25 11:49 UTC, Shisui6 approved these changes
Hi @MasumaJaffery, 

# Approved 🪄
Your project is complete! There is nothing else to say other than... it's time to merge it 💎
Congratulations! 🎉 

## Highlights 🎯
- Home and about pages created ✅


## Optional suggestions 🪶

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 11:52 UTC, merged